### ISSUE TITLE
Stitch not showing in editor

### ISSUE THREAD

**Issue by drandell** [paulloz/godot-ink#28]
Hi, 

The following little test ink file containing a stitch;
```
-> top_knot

=== top_knot ===
Hello world!
* [How are you] -> okay

=== okay 
I am okay 
-> DONE

-> END
```

Would display this in ink editor;
![image](https://user-images.githubusercontent.com/393945/104071692-94cf7180-5201-11eb-8bc1-a246a54b277d.png)

Inside of the Ink preview in Godot, it looks like this;
![image](https://user-images.githubusercontent.com/393945/104071728-a7e24180-5201-11eb-8e83-39a042565731.png)

Not sure if related to #23

**Comment by paulloz** [comment]
Yes, it probably is the exact same bug.

**Comment by paulloz** [comment]
This is fixed on `master`.

**Comment by drandell** [comment]
@paulloz should i be using 0.6 or master directly? 
Trying to load right now, its just failing;
![image](https://user-images.githubusercontent.com/393945/105629602-d97f1d80-5e3b-11eb-980b-eb50b1e5d754.png)

**Comment by paulloz** [comment]
@drandell you might've retrieved the branch between a40ca9d0f69302c6cbdc31ad1a9ec0e77c39fda6 and 8f18b4f6d7c12c92e087893b9c3de375921ab583.  
The active branch isn't always going to be stable (sorry about that). As this fix seems rather important, I'll draft a release quickly.  
If you have issues with Godot crashing due to having broken compiled scripts, close the editor, delete the project's `.mono` folder,  and it'll be OK.

**Comment by drandell** [comment]
I deleted my mono folder, rebuilt project. Then re-enabled the ink plugin. Deleted the failing import and tried to re-import and its still failing, in the output i see;
![image](https://user-images.githubusercontent.com/393945/105631839-5f08ca80-5e48-11eb-8102-b922def30fb4.png)

**Comment by paulloz** [comment]
I'd say the path to inklecate has been reset probably.

**Comment by drandell** [comment]
@paulloz yeah that was the case :). 
The bug is still present for me; (im using master)
![image](https://user-images.githubusercontent.com/393945/105635570-73a28e00-5e5b-11eb-9465-d2e750f0949e.png)

**Comment by paulloz** [comment]
![Godot_v3 2 3-stable_mono_win64_FdwMWfrzP0](https://user-images.githubusercontent.com/437025/105636381-7788dd00-5e68-11eb-9908-7d5a07bfbe72.png)

In **1**, the current `master` (151ebf3).
In **2**, the file you provided at the [top of this thread](#issue-782437268).
In **3**, the result (identical to the one displayed in Inky).

Unless I'm missing something I can't seem to reproduce.  
In any case, this issue will stay open as long as the fix isn't in a stable release.

**Comment by drandell** [comment]
No you are right. I had changed my test.ink file and had forgotten to re-update. Happy for this to be closed! 

The one thing that threw me off was that once i reach the end of a story, i dont get that visual confirmation. SO in the ink editor you get "end of story". I think this would be a great addition 

![image](https://user-images.githubusercontent.com/393945/105638066-a901a880-5e68-11eb-9432-bf635ca9eb68.png)
